# Generated by Django 3.2.15 on 2022-10-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DB_teach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('course', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(default='', max_length=255)),
                ('owner', models.CharField(default='', max_length=255)),
                ('location', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor_infor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=255)),
                ('expertise', models.CharField(default='', max_length=255)),
                ('experience', models.CharField(default='', max_length=255)),
                ('performance', models.ImageField(blank=True, null=True, upload_to='static/IMG')),
                ('VDO', models.FileField(upload_to='static/video')),
                ('tutor', models.ManyToManyField(to='teach.Tutor')),
            ],
        ),
    ]
